services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: file2qr_user
      POSTGRES_PASSWORD: file2qr_password
      POSTGRES_DB: file2qr
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
