# Generated by Django 6.1.1 on 2026-09-09 04:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        ('qr_codes', '0002_initial'),
        ('sharing', '0002_sharelink_download_count_sharelink_expires_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('VIEW', 'View'), ('DOWNLOAD', 'Download'), ('QR_SCAN', 'QR Scan'), ('PASSWORD_SUCCESS', 'Password Success'), ('PASSWORD_FAILED', 'Password Failed'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('browser', models.CharField(blank=True, max_length=50, null=True)),
                ('os', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('referrer', models.URLField(blank=True, max_length=1024, null=True)),
                ('success', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='files.file')),
                ('qr_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='qr_codes.qrcode')),
                ('share_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sharing.sharelink')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['share_link'], name='analytics_s_share_l_71f428_idx'), models.Index(fields=['file'], name='analytics_s_file_id_969513_idx'), models.Index(fields=['event_type'], name='analytics_s_event_t_75d58c_idx'), models.Index(fields=['created_at'], name='analytics_s_created_fe0f33_idx'), models.Index(fields=['share_link', 'created_at'], name='analytics_s_share_l_e32734_idx'), models.Index(fields=['file', 'created_at'], name='analytics_s_file_id_84f8f0_idx')],
            },
        ),
    ]
