# Generated by Django 6.1.1 on 2026-09-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharelink',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sharelink',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sharelink',
            name='max_downloads',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sharelink',
            name='password_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
