# Generated by Django 6.1.1 on 2026-09-08 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qr_codes', '0001_initial'),
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='share_link',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='sharing.sharelink'),
        ),
    ]
