# Generated by Django 6.1.1 on 2026-09-08 14:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('storage_key', models.CharField(max_length=512, unique=True)),
                ('file_size', models.BigIntegerField()),
                ('content_type', models.CharField(max_length=128)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UPLOADING', 'Uploading'), ('ACTIVE', 'Active'), ('FAILED', 'Failed'), ('DELETED', 'Deleted')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'status'], name='files_file_owner_i_1c981d_idx'), models.Index(fields=['storage_key'], name='files_file_storage_3b902c_idx')],
            },
        ),
    ]
